version: "3.3"

services:
  web:
    build: .
    volumes:
      - .:/app:delegated
      - ./.container:/root
    command:
      - bundle
      - exec
      - rackup
      - --host
      - 0.0.0.0
    ports:
      - 9292:9292
